### ISSUE TITLE
Greifenburg, Austria: add more info

### ISSUE THREAD

**Issue by gara-z** [BHGC/website#101]
Add links with more details on Greifburg site Emberger Alm:

Paragling/Hang gliding at Emberger Alm: https://www.embergeralm.info/paragleiten-drachenfliegen_D.html
Cross Country Guide to Greifenburg (2014): https://xcmag.com/travel-guide/guide-to-greifenburg-austria/?v=79cba1185463
DHV info Emberger Alm - Greifenburg: https://www.dhv.de/db2/details.php?qi=glp_details&item=1305

**Comment by gara-z** [comment]
Typos correction

**Comment by HenrikBengtsson** [comment]
Added; https://www.bhgc.org/sites/alps/index.html#site_greifenburg-austria
