### ISSUE TITLE
SITE: Owens

### ISSUE THREAD

**Issue by pretzilla** [BHGC/website#22]
Wx collection of weather stations and forecasts: http://sierrawx.com/

page made by Russell Cohen 
https://www.facebook.com/rcohen

**Comment by HenrikBengtsson** [comment]
Site seems down. Not sure when it last worked, but it now says "sierrawx.com, expired on 04/27/2024 and is not available at this time.".

Looking at https://github.com/rcoh, it's not listed there, and he's now in Boston, so the site is probably obsolete.

I close ...
